services:   

  server:
    build:
      context: .
      dockerfile: ./deploy/docker/Dockerfile
      target: builder
    command: go run ./cmd/server
    env_file: .env
    volumes:
      - .:/usr/app/server
    ports:
      - '8080:8080'
    restart: unless-stopped