services:   
  redis:
    image: redis:8.0-M02-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  server:
    build:
      context: .
      dockerfile: ./deploy/docker/Dockerfile
      target: builder
    command: go run ./cmd/server
    env_file: .env
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - .:/usr/app/server
    ports:
      - '8080:8080'
    restart: unless-stopped

volumes:
  redis_data: